server:
  port: 8085
  servlet:
    context-path: /api/v1/user-management

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: volunteer-app-backend

  datasource:
    url: jdbc:postgresql://db-postgresql-volunteerapp-do-user-10100634-0.e.db.ondigitalocean.com:25060/defaultdb
    username: doadmin
    password: AVNS_d2dvzrgSgfOd6J8wJPo
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: none
    show-sql: true

social:
  googleClientId: "142245667829-afpupoofnh363onmduragfrhduii4jj5.apps.googleusercontent.com"


request-mapping:
  controller:
    user: users
    volunteer: volunteers
    organization: organizations