name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build_develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build and push Docker image for develop
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/back-volunteerapp:develop .
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/back-volunteerapp:develop

      - name: Run Docker image locally for testing
        run: |
          docker run -d --name back-volunteerapp-test -p 8085:8085 ghcr.io/${{ secrets.GHCR_USERNAME }}/back-volunteerapp:develop

  build_main:
    runs-on: ubuntu-latest
    needs: build_develop
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Merge develop into main
        run: |
          git config --global user.email "santiagomejiaf@javeriana.edu.co"
          git config --global user.name "SantiagoMejiaF"
          git remote set-url origin https://x-access-token:${{ secrets.GHCR_TOKEN }}@github.com/Asesor-Digital/back-volunteerapp.git
          git checkout main
          git pull origin main
          git merge develop --no-ff --no-commit
          git commit -m "Merge branch 'develop' into main"
          git push origin main

      - name: Build and push Docker image for main
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/back-volunteerapp:main .
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/back-volunteerapp:main

  deploy:
    needs: build_main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} -p ${{ secrets.GHCR_TOKEN }}
            docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/back-volunteerapp:main
            docker stop back-volunteerapp || true
            docker rm back-volunteerapp || true
            docker run -d --name back-volunteerapp -p 8085:8085 ghcr.io/${{ secrets.GHCR_USERNAME }}/back-volunteerapp:main
