name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/back-volunteerapp:${{ github.sha }} .
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/back-volunteerapp:${{ github.sha }}

      - name: Update develop branch
        if: github.ref == 'refs/heads/develop'
        run: |
          git config --global user.email "santiagomejiaf@javeriana.edu.co"
          git config --global user.name "SantiagoMejiaF"
          git checkout develop
          git pull origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Push to main
        if: github.ref == 'refs/heads/develop'
        run: |
          git config --global user.email "santiagomejiaf@javeriana.edu.co"
          git config --global user.name "SantiagoMejiaF"
          git checkout main
          git merge develop
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to DigitalOcean
        run: |
          doctl auth init -t ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          doctl apps update back-volunteerapp-id --spec .do/app.yaml
