name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build_develop:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build and push Docker image for develop
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/back-volunteerapp:develop .
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/back-volunteerapp:develop

      - name: Run Docker image locally for testing
        run: |
          docker run -d --name back-volunteerapp-test -p 8085:8085 ghcr.io/${{ secrets.GHCR_USERNAME }}/back-volunteerapp:develop

  deploy:
    runs-on: ubuntu-latest
    needs: build_develop

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} -p ${{ secrets.GHCR_TOKEN }}
            fuser -k 8085/tcp || true
            docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/back-volunteerapp:develop
            docker stop back-volunteerapp-develop || true
            docker rm back-volunteerapp-develop || true
            docker run -d --name back-volunteerapp-develop -p 8085:8085 ghcr.io/${{ secrets.GHCR_USERNAME }}/back-volunteerapp:develop