name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build_deploy_develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build and push Docker image for develop
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/back-volunteerapp:develop .
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/back-volunteerapp:develop

      - name: SSH to server and deploy develop image
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} -p ${{ secrets.GHCR_TOKEN }}
            docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/back-volunteerapp:develop
            docker stop back-volunteerapp-develop || true
            docker rm back-volunteerapp-develop || true
            docker run -d --name back-volunteerapp-develop -p 8086:8085 ghcr.io/${{ secrets.GHCR_USERNAME }}/back-volunteerapp:develop
            sudo sed -i 's/8085/8086/' /etc/nginx/sites-available/default
            sudo nginx -s reload
            sleep 5
            docker stop back-volunteerapp || true
            docker rm back-volunteerapp || true
            docker rename back-volunteerapp-develop back-volunteerapp
            sudo sed -i 's/8086/8085/' /etc/nginx/sites-available/default
            sudo nginx -s reload
