name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/back-volunteerapp:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository }}/back-volunteerapp:${{ github.sha }}
          docker tag ghcr.io/${{ github.repository }}/back-volunteerapp:${{ github.sha }} ghcr.io/${{ github.repository }}/back-volunteerapp:latest
          docker push ghcr.io/${{ github.repository }}/back-volunteerapp:latest

      - name: Push to main
        if: github.ref == 'refs/heads/develop'
        run: |
          git config --global user.email "santiagomejiaf@javeriana.edu.co"
          git config --global user.name "Santiago Mejia Fernandez"
          git checkout main
          git merge develop
          git push origin main

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository }}/back-volunteerapp:latest
            docker stop back-volunteerapp || true
            docker rm back-volunteerapp || true
            docker run -d --name back-volunteerapp -p 8085:8085 ghcr.io/${{ github.repository }}/back-volunteerapp:latest